version: '3.1'

services:
  springboot:
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=qadb
    - MONGO_DB_PASSWORD=qadb123 
  mongo:    
    environment:
    - MONGO_INITDB_ROOT_USERNAME=qadb
    - MONGO_INITDB_ROOT_PASSWORD=qadb123
